site_name: Hướng dẫn Xpenology toàn tập
theme:
  name: material
  language: vi
  palette:
    scheme: slate
  features:
    - search.suggest
extra:
  generator: false
repo_url: https://github.com/luutuananh/xpenology
plugins:
  - search:
      lang: vi
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
      locale: vi
nav:
  - 'index.md'
  - 'caidat.md'
  - 'sudung.md'