site_name: Hướng dẫn Xpenology toàn tập
theme:
  name: material
  font: 
    text: Inconsolata
  language: vi
  palette:
    scheme: slate
repo_url: https://github.com/luutuananh/xpenology
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
      locale: vi
nav:
  - 'index.md'
  - 'caidat.md'
  - 'sudung.md'