site_name: Hướng dẫn Xpenology toàn tập
theme:
  name: material
  language: vi
  palette:
    scheme: slate
repo_url: https://github.com/luutuananh/xpenology
plugins:
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
      type: timeago
nav:
  - 'index.md'
  - 'caidat.md'
  - 'sudung.md'