site_name: Hướng dẫn Xpenology toàn tập
theme:
  name: material
  language: vi
  palette:
    scheme: slate
repo_url: https://github.com/luutuananh/xpenology
plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
      locale: vi
extra:
  generator: false
  social:
  - icon: fontawesome/brands/facebook 
    link: https://facebook.com/
    name: Nhóm facebook Xpenology trên Facebook
copyright: Copyright &copy; 2023 luutuananh
nav:
  - 'index.md'
  - 'caidat.md'
  - 'sudung.md'